paths:
  working_directory: .
  database: ./final_ARD_projects_latest.db
  raw_reads: ./raw_reads_projects/
  analysis_files: ./analysis_files/
  analysis_datasets: ./analysis_datasets/
  pipeline_runs: ./pipeline_runs/
  python_scripts: ./scripts/python/