graph LR

AU10["AU 10"]
AU11["AU 11"]
AU12["AU 12"]
AU13["AU 13"]
AU14["AU 14"]
AU15["AU 15"]
AU16["AU 16"]
AU17["AU 17"]
AU18["AU 18"]
AU19["AU 19"]
AU1["AU 1"]
AU20["AU 20"]
AU21["AU 21"]
AU22["AU 22"]
AU23["AU 23"]
AU24["AU 24"]
AU25["AU 25"]
AU26["AU 26"]
AU27["AU 27"]
AU28["AU 28"]
AU29["AU 29"]
AU2["AU 2"]
AU30["AU 30"]
AU31["AU 31"]
AU32["AU 32"]
AU33["AU 33"]
AU34["AU 34"]
AU35["AU 35"]
AU36["AU 36"]
AU37["AU 37"]
AU38["AU 38"]
AU39["AU 39"]
AU3["AU 3"]
AU40["AU 40"]
AU41["AU 41"]
AU42["AU 42"]
AU43["AU 43"]
AU44["AU 44"]
AU45["AU 45"]
AU46["AU 46"]
AU47["AU 47"]
AU48["AU 48"]
AU49["AU 49"]
AU4["AU 4"]
AU50["AU 50"]
AU51["AU 51"]
AU52["AU 52"]
AU53["AU 53"]
AU54["AU 54"]
AU55["AU 55"]
AU56["AU 56"]
AU57["AU 57"]
AU58["AU 58"]
AU59["AU 59"]
AU5["AU 5"]
AU60["AU 60"]
AU61["AU 61"]
AU62["AU 62"]
AU63["AU 63"]
AU64["AU 64"]
AU65["AU 65"]
AU66["AU 66"]
AU67["AU 67"]
AU68["AU 68"]
AU69["AU 69"]
AU6["AU 6"]
AU70["AU 70"]
AU71["AU 71"]
AU72["AU 72"]
AU73["AU 73"]
AU74["AU 74"]
AU75["AU 75"]
AU76["AU 76"]
AU77["AU 77"]
AU78["AU 78"]
AU79["AU 79"]
AU7["AU 7"]
AU80["AU 80"]
AU8["AU 8"]
AU9["AU 9"]
L10["Library 10"]
L11["Library 11"]
L12["Library 12"]
L13["Library 13"]
L14["Library 14"]
L15["Library 15"]
L16["Library 16"]
L17["Library 17"]
L18["Library 18"]
L19["Library 19"]
L1["Library 1"]
L20["Library 20"]
L21["Library 21"]
L22["Library 22"]
L23["Library 23"]
L24["Library 24"]
L25["Library 25"]
L26["Library 26"]
L27["Library 27"]
L28["Library 28"]
L29["Library 29"]
L2["Library 2"]
L30["Library 30"]
L31["Library 31"]
L32["Library 32"]
L33["Library 33"]
L34["Library 34"]
L35["Library 35"]
L36["Library 36"]
L37["Library 37"]
L38["Library 38"]
L39["Library 39"]
L3["Library 3"]
L40["Library 40"]
L41["Library 41"]
L42["Library 42"]
L43["Library 43"]
L44["Library 44"]
L45["Library 45"]
L46["Library 46"]
L47["Library 47"]
L48["Library 48"]
L49["Library 49"]
L4["Library 4"]
L50["Library 50"]
L51["Library 51"]
L52["Library 52"]
L53["Library 53"]
L54["Library 54"]
L55["Library 55"]
L56["Library 56"]
L57["Library 57"]
L58["Library 58"]
L59["Library 59"]
L5["Library 5"]
L60["Library 60"]
L61["Library 61"]
L62["Library 62"]
L63["Library 63"]
L64["Library 64"]
L65["Library 65"]
L66["Library 66"]
L67["Library 67"]
L68["Library 68"]
L69["Library 69"]
L6["Library 6"]
L70["Library 70"]
L71["Library 71"]
L72["Library 72"]
L73["Library 73"]
L74["Library 74"]
L75["Library 75"]
L76["Library 76"]
L77["Library 77"]
L78["Library 78"]
L79["Library 79"]
L7["Library 7"]
L80["Library 80"]
L8["Library 8"]
L9["Library 9"]
S100["MZBS_5"]
S101["MZR_1"]
S102["MZR_2"]
S103["MZR_3"]
S104["MZR_4"]
S105["MZR_5"]
S106["MZRS_1"]
S107["MZRS_2"]
S108["MZRS_3"]
S109["MZRS_4"]
S110["MZRS_5"]
S111["R29_1"]
S112["R29_2"]
S113["R29_3"]
S114["R29_4"]
S115["R29_5"]
S36["Control_1"]
S37["Control_2"]
S38["Control_3"]
S39["Control_4"]
S40["Control_5"]
S41["GZ_BS_1"]
S42["GZ_BS_2"]
S43["GZ_BS_3"]
S44["GZ_BS_4"]
S45["GZ_BS_5"]
S46["GZ_R_1"]
S47["GZ_R_2"]
S48["GZ_R_3"]
S49["GZ_R_4"]
S50["GZ_R_5"]
S51["GZ_RS_1"]
S52["GZ_RS_2"]
S53["GZ_RS_3"]
S54["GZ_RS_4"]
S55["GZ_RS_5"]
S56["GZBS_1"]
S57["GZBS_2"]
S58["GZBS_3"]
S59["GZBS_4"]
S60["GZBS_5"]
S61["GZR_1"]
S62["GZR_2"]
S63["GZR_3"]
S64["GZR_4"]
S65["GZR_5"]
S66["GZRS_1"]
S67["GZRS_2"]
S68["GZRS_3"]
S69["GZRS_4"]
S70["GZRS_5"]
S71["Lysine_1"]
S72["Lysine_2"]
S73["Lysine_3"]
S74["Lysine_4"]
S75["Lysine_5"]
S76["Lysine+R29_1"]
S77["Lysine+R29_2"]
S78["Lysine+R29_3"]
S79["Lysine+R29_4"]
S80["Lysine+R29_5"]
S81["MZ_BS_1"]
S82["MZ_BS_2"]
S83["MZ_BS_3"]
S84["MZ_BS_4"]
S85["MZ_BS_5"]
S86["MZ_R_1"]
S87["MZ_R_2"]
S88["MZ_R_3"]
S89["MZ_R_4"]
S90["MZ_R_5"]
S91["MZ_RS_1"]
S92["MZ_RS_2"]
S93["MZ_RS_3"]
S94["MZ_RS_4"]
S95["MZ_RS_5"]
S96["MZBS_1"]
S97["MZBS_2"]
S98["MZBS_3"]
S99["MZBS_4"]
SO100["SO 100"]
SO101["SO 101"]
SO102["SO 102"]
SO103["SO 103"]
SO104["SO 104"]
SO105["SO 105"]
SO106["SO 106"]
SO107["SO 107"]
SO108["SO 108"]
SO109["SO 109"]
SO110["SO 110"]
SO111["SO 111"]
SO112["SO 112"]
SO113["SO 113"]
SO114["SO 114"]
SO115["SO 115"]
SO116["SO 116"]
SO37["SO 37"]
SO38["SO 38"]
SO39["SO 39"]
SO40["SO 40"]
SO41["SO 41"]
SO42["SO 42"]
SO43["SO 43"]
SO44["SO 44"]
SO45["SO 45"]
SO46["SO 46"]
SO47["SO 47"]
SO48["SO 48"]
SO49["SO 49"]
SO50["SO 50"]
SO51["SO 51"]
SO52["SO 52"]
SO53["SO 53"]
SO54["SO 54"]
SO55["SO 55"]
SO56["SO 56"]
SO57["SO 57"]
SO58["SO 58"]
SO59["SO 59"]
SO60["SO 60"]
SO61["SO 61"]
SO62["SO 62"]
SO63["SO 63"]
SO64["SO 64"]
SO65["SO 65"]
SO66["SO 66"]
SO67["SO 67"]
SO68["SO 68"]
SO69["SO 69"]
SO70["SO 70"]
SO71["SO 71"]
SO72["SO 72"]
SO73["SO 73"]
SO74["SO 74"]
SO75["SO 75"]
SO76["SO 76"]
SO77["SO 77"]
SO78["SO 78"]
SO79["SO 79"]
SO80["SO 80"]
SO81["SO 81"]
SO82["SO 82"]
SO83["SO 83"]
SO84["SO 84"]
SO85["SO 85"]
SO86["SO 86"]
SO87["SO 87"]
SO88["SO 88"]
SO89["SO 89"]
SO90["SO 90"]
SO91["SO 91"]
SO92["SO 92"]
SO93["SO 93"]
SO94["SO 94"]
SO95["SO 95"]
SO96["SO 96"]
SO97["SO 97"]
SO98["SO 98"]
SO99["SO 99"]

AU1 --> SO37
AU10 --> SO46
AU11 --> SO47
AU12 --> SO48
AU13 --> SO49
AU14 --> SO50
AU15 --> SO51
AU16 --> SO52
AU17 --> SO53
AU18 --> SO54
AU19 --> SO55
AU2 --> SO38
AU20 --> SO56
AU21 --> SO57
AU22 --> SO58
AU23 --> SO59
AU24 --> SO60
AU25 --> SO61
AU26 --> SO62
AU27 --> SO63
AU28 --> SO64
AU29 --> SO65
AU3 --> SO39
AU30 --> SO66
AU31 --> SO67
AU32 --> SO68
AU33 --> SO69
AU34 --> SO70
AU35 --> SO71
AU36 --> SO72
AU37 --> SO73
AU38 --> SO74
AU39 --> SO75
AU4 --> SO40
AU40 --> SO76
AU41 --> SO77
AU42 --> SO78
AU43 --> SO79
AU44 --> SO80
AU45 --> SO81
AU46 --> SO82
AU47 --> SO83
AU48 --> SO84
AU49 --> SO85
AU5 --> SO41
AU50 --> SO86
AU51 --> SO87
AU52 --> SO88
AU53 --> SO89
AU54 --> SO90
AU55 --> SO91
AU56 --> SO92
AU57 --> SO93
AU58 --> SO94
AU59 --> SO95
AU6 --> SO42
AU60 --> SO96
AU61 --> SO97
AU62 --> SO98
AU63 --> SO99
AU64 --> SO100
AU65 --> SO101
AU66 --> SO102
AU67 --> SO103
AU68 --> SO104
AU69 --> SO105
AU7 --> SO43
AU70 --> SO106
AU71 --> SO107
AU72 --> SO108
AU73 --> SO109
AU74 --> SO110
AU75 --> SO111
AU76 --> SO112
AU77 --> SO113
AU78 --> SO114
AU79 --> SO115
AU8 --> SO44
AU80 --> SO116
AU9 --> SO45
L1 --> AU1
L10 --> AU10
L11 --> AU11
L12 --> AU12
L13 --> AU13
L14 --> AU14
L15 --> AU15
L16 --> AU16
L17 --> AU17
L18 --> AU18
L19 --> AU19
L2 --> AU2
L20 --> AU20
L21 --> AU21
L22 --> AU22
L23 --> AU23
L24 --> AU24
L25 --> AU25
L26 --> AU26
L27 --> AU27
L28 --> AU28
L29 --> AU29
L3 --> AU3
L30 --> AU30
L31 --> AU31
L32 --> AU32
L33 --> AU33
L34 --> AU34
L35 --> AU35
L36 --> AU36
L37 --> AU37
L38 --> AU38
L39 --> AU39
L4 --> AU4
L40 --> AU40
L41 --> AU41
L42 --> AU42
L43 --> AU43
L44 --> AU44
L45 --> AU45
L46 --> AU46
L47 --> AU47
L48 --> AU48
L49 --> AU49
L5 --> AU5
L50 --> AU50
L51 --> AU51
L52 --> AU52
L53 --> AU53
L54 --> AU54
L55 --> AU55
L56 --> AU56
L57 --> AU57
L58 --> AU58
L59 --> AU59
L6 --> AU6
L60 --> AU60
L61 --> AU61
L62 --> AU62
L63 --> AU63
L64 --> AU64
L65 --> AU65
L66 --> AU66
L67 --> AU67
L68 --> AU68
L69 --> AU69
L7 --> AU7
L70 --> AU70
L71 --> AU71
L72 --> AU72
L73 --> AU73
L74 --> AU74
L75 --> AU75
L76 --> AU76
L77 --> AU77
L78 --> AU78
L79 --> AU79
L8 --> AU8
L80 --> AU80
L9 --> AU9
S100 --> L36
S101 --> L34
S102 --> L33
S103 --> L32
S104 --> L31
S105 --> L30
S106 --> L29
S107 --> L28
S108 --> L27
S109 --> L26
S110 --> L25
S111 --> L12
S112 --> L11
S113 --> L10
S114 --> L9
S115 --> L8
S36 --> L23
S37 --> L22
S38 --> L21
S39 --> L20
S40 --> L19
S41 --> L80
S42 --> L79
S43 --> L68
S44 --> L57
S45 --> L46
S46 --> L35
S47 --> L24
S48 --> L13
S49 --> L2
S50 --> L1
S51 --> L78
S52 --> L77
S53 --> L76
S54 --> L75
S55 --> L74
S56 --> L73
S57 --> L72
S58 --> L71
S59 --> L70
S60 --> L69
S61 --> L67
S62 --> L66
S63 --> L65
S64 --> L64
S65 --> L63
S66 --> L62
S67 --> L61
S68 --> L60
S69 --> L59
S70 --> L58
S71 --> L18
S72 --> L17
S73 --> L16
S74 --> L15
S75 --> L14
S76 --> L7
S77 --> L6
S78 --> L5
S79 --> L4
S80 --> L3
S81 --> L56
S82 --> L55
S83 --> L54
S84 --> L53
S85 --> L52
S86 --> L51
S87 --> L50
S88 --> L49
S89 --> L48
S90 --> L47
S91 --> L45
S92 --> L44
S93 --> L43
S94 --> L42
S95 --> L41
S96 --> L40
S97 --> L39
S98 --> L38
S99 --> L37

subgraph Dataset_Legend
LEG_DS_1["Dataset 1"]
LEG_DS_2["Dataset 2"]
end

subgraph Run_Legend
LEG_RUN_1["Run 1"]
LEG_RUN_2["Run 2"]
end

subgraph Amplicon_Legend
LEG_AMP_7["Amplicon 7"]
LEG_AMP_11["Amplicon 11"]
end

classDef ds_2 fill:#377eb8,stroke:#444,stroke-width:2px
class LEG_DS_2 ds_2
classDef ds_1 fill:#e41a1c,stroke:#444,stroke-width:2px
class LEG_DS_1 ds_1
classDef run_2 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class LEG_RUN_2 run_2
classDef run_1 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class LEG_RUN_1 run_1
classDef amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class LEG_AMP_11 amp_11
classDef amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class LEG_AMP_7 amp_7
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU23 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU22 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU21 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU20 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU19 au_d2_r2
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU80 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU79 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU68 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU57 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU46 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU35 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU24 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU13 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU2 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU1 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU78 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU77 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU76 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU75 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU74 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU73 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU72 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU71 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU70 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU69 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU67 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU66 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU65 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU64 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU63 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU62 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU61 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU60 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU59 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU58 au_d1_r1
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU18 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU17 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU16 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU15 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU14 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU7 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU6 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU5 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU4 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU3 au_d2_r2
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU56 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU55 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU54 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU53 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU52 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU51 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU50 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU49 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU48 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU47 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU45 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU44 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU43 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU42 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU41 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU40 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU39 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU38 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU37 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU36 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU34 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU33 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU32 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU31 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU30 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU29 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU28 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU27 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU26 au_d1_r1
classDef au_d1_r1 fill:#e41a1c,stroke:#e41a1c,stroke-width:5px
class AU25 au_d1_r1
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU12 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU11 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU10 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU9 au_d2_r2
classDef au_d2_r2 fill:#377eb8,stroke:#377eb8,stroke-width:5px
class AU8 au_d2_r2
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L23 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L22 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L21 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L20 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L19 lib_amp_11
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L80 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L79 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L68 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L57 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L46 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L35 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L24 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L13 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L2 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L1 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L78 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L77 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L76 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L75 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L74 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L73 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L72 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L71 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L70 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L69 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L67 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L66 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L65 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L64 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L63 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L62 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L61 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L60 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L59 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L58 lib_amp_7
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L18 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L17 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L16 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L15 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L14 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L7 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L6 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L5 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L4 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L3 lib_amp_11
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L56 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L55 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L54 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L53 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L52 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L51 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L50 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L49 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L48 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L47 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L45 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L44 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L43 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L42 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L41 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L40 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L39 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L38 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L37 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L36 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L34 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L33 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L32 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L31 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L30 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L29 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L28 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L27 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L26 lib_amp_7
classDef lib_amp_7 fill:#ffffff,stroke:#e41a1c,stroke-width:5px
class L25 lib_amp_7
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L12 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L11 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L10 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L9 lib_amp_11
classDef lib_amp_11 fill:#ffffff,stroke:#377eb8,stroke-width:5px
class L8 lib_amp_11
classDef missing fill:#ff9999,stroke:#cc0000,stroke-width:3px